package com.fhq.model;

import java.util.Date;

public class CrrInventory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crr_inventory.id_key
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private Integer idKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crr_inventory.asset_no
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private String assetNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crr_inventory.asset_quantity
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private String assetQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crr_inventory.last_time
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private Date lastTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crr_inventory.last_opr
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private String lastOpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crr_inventory.job_flag
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private Integer jobFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crr_inventory.id_key
     *
     * @return the value of crr_inventory.id_key
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public Integer getIdKey() {
        return idKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crr_inventory.id_key
     *
     * @param idKey the value for crr_inventory.id_key
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setIdKey(Integer idKey) {
        this.idKey = idKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crr_inventory.asset_no
     *
     * @return the value of crr_inventory.asset_no
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public String getAssetNo() {
        return assetNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crr_inventory.asset_no
     *
     * @param assetNo the value for crr_inventory.asset_no
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setAssetNo(String assetNo) {
        this.assetNo = assetNo == null ? null : assetNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crr_inventory.asset_quantity
     *
     * @return the value of crr_inventory.asset_quantity
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public String getAssetQuantity() {
        return assetQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crr_inventory.asset_quantity
     *
     * @param assetQuantity the value for crr_inventory.asset_quantity
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setAssetQuantity(String assetQuantity) {
        this.assetQuantity = assetQuantity == null ? null : assetQuantity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crr_inventory.last_time
     *
     * @return the value of crr_inventory.last_time
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crr_inventory.last_time
     *
     * @param lastTime the value for crr_inventory.last_time
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crr_inventory.last_opr
     *
     * @return the value of crr_inventory.last_opr
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public String getLastOpr() {
        return lastOpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crr_inventory.last_opr
     *
     * @param lastOpr the value for crr_inventory.last_opr
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setLastOpr(String lastOpr) {
        this.lastOpr = lastOpr == null ? null : lastOpr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crr_inventory.job_flag
     *
     * @return the value of crr_inventory.job_flag
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public Integer getJobFlag() {
        return jobFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crr_inventory.job_flag
     *
     * @param jobFlag the value for crr_inventory.job_flag
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setJobFlag(Integer jobFlag) {
        this.jobFlag = jobFlag;
    }
}