package com.fhq.model;

import java.util.Date;

public class InventoryMgt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_mgt.id_key
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private Integer idKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_mgt.asset_no
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private String assetNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_mgt.inventory_type
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private String inventoryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_mgt.instore_time
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private Date instoreTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_mgt.instore_quantity
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private String instoreQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_mgt.asset_orgn_value
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private Double assetOrgnValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_mgt.asset_pur_dept
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private String assetPurDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_mgt.supplier
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private String supplier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_mgt.supplier_phone
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private String supplierPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_mgt.outstore_time
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private Date outstoreTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_mgt.outstore_quantity
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private String outstoreQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_mgt.asset_duty_man
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private String assetDutyMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_mgt.handle_man
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private String handleMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_mgt.last_asset_value
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private Double lastAssetValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_mgt.last_time
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private Date lastTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_mgt.last_opr
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private String lastOpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_mgt.job_flag
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private Integer jobFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_mgt.id_key
     *
     * @return the value of inventory_mgt.id_key
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public Integer getIdKey() {
        return idKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_mgt.id_key
     *
     * @param idKey the value for inventory_mgt.id_key
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setIdKey(Integer idKey) {
        this.idKey = idKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_mgt.asset_no
     *
     * @return the value of inventory_mgt.asset_no
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public String getAssetNo() {
        return assetNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_mgt.asset_no
     *
     * @param assetNo the value for inventory_mgt.asset_no
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setAssetNo(String assetNo) {
        this.assetNo = assetNo == null ? null : assetNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_mgt.inventory_type
     *
     * @return the value of inventory_mgt.inventory_type
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public String getInventoryType() {
        return inventoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_mgt.inventory_type
     *
     * @param inventoryType the value for inventory_mgt.inventory_type
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setInventoryType(String inventoryType) {
        this.inventoryType = inventoryType == null ? null : inventoryType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_mgt.instore_time
     *
     * @return the value of inventory_mgt.instore_time
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public Date getInstoreTime() {
        return instoreTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_mgt.instore_time
     *
     * @param instoreTime the value for inventory_mgt.instore_time
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setInstoreTime(Date instoreTime) {
        this.instoreTime = instoreTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_mgt.instore_quantity
     *
     * @return the value of inventory_mgt.instore_quantity
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public String getInstoreQuantity() {
        return instoreQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_mgt.instore_quantity
     *
     * @param instoreQuantity the value for inventory_mgt.instore_quantity
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setInstoreQuantity(String instoreQuantity) {
        this.instoreQuantity = instoreQuantity == null ? null : instoreQuantity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_mgt.asset_orgn_value
     *
     * @return the value of inventory_mgt.asset_orgn_value
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public Double getAssetOrgnValue() {
        return assetOrgnValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_mgt.asset_orgn_value
     *
     * @param assetOrgnValue the value for inventory_mgt.asset_orgn_value
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setAssetOrgnValue(Double assetOrgnValue) {
        this.assetOrgnValue = assetOrgnValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_mgt.asset_pur_dept
     *
     * @return the value of inventory_mgt.asset_pur_dept
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public String getAssetPurDept() {
        return assetPurDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_mgt.asset_pur_dept
     *
     * @param assetPurDept the value for inventory_mgt.asset_pur_dept
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setAssetPurDept(String assetPurDept) {
        this.assetPurDept = assetPurDept == null ? null : assetPurDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_mgt.supplier
     *
     * @return the value of inventory_mgt.supplier
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_mgt.supplier
     *
     * @param supplier the value for inventory_mgt.supplier
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_mgt.supplier_phone
     *
     * @return the value of inventory_mgt.supplier_phone
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public String getSupplierPhone() {
        return supplierPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_mgt.supplier_phone
     *
     * @param supplierPhone the value for inventory_mgt.supplier_phone
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setSupplierPhone(String supplierPhone) {
        this.supplierPhone = supplierPhone == null ? null : supplierPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_mgt.outstore_time
     *
     * @return the value of inventory_mgt.outstore_time
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public Date getOutstoreTime() {
        return outstoreTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_mgt.outstore_time
     *
     * @param outstoreTime the value for inventory_mgt.outstore_time
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setOutstoreTime(Date outstoreTime) {
        this.outstoreTime = outstoreTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_mgt.outstore_quantity
     *
     * @return the value of inventory_mgt.outstore_quantity
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public String getOutstoreQuantity() {
        return outstoreQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_mgt.outstore_quantity
     *
     * @param outstoreQuantity the value for inventory_mgt.outstore_quantity
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setOutstoreQuantity(String outstoreQuantity) {
        this.outstoreQuantity = outstoreQuantity == null ? null : outstoreQuantity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_mgt.asset_duty_man
     *
     * @return the value of inventory_mgt.asset_duty_man
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public String getAssetDutyMan() {
        return assetDutyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_mgt.asset_duty_man
     *
     * @param assetDutyMan the value for inventory_mgt.asset_duty_man
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setAssetDutyMan(String assetDutyMan) {
        this.assetDutyMan = assetDutyMan == null ? null : assetDutyMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_mgt.handle_man
     *
     * @return the value of inventory_mgt.handle_man
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public String getHandleMan() {
        return handleMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_mgt.handle_man
     *
     * @param handleMan the value for inventory_mgt.handle_man
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setHandleMan(String handleMan) {
        this.handleMan = handleMan == null ? null : handleMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_mgt.last_asset_value
     *
     * @return the value of inventory_mgt.last_asset_value
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public Double getLastAssetValue() {
        return lastAssetValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_mgt.last_asset_value
     *
     * @param lastAssetValue the value for inventory_mgt.last_asset_value
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setLastAssetValue(Double lastAssetValue) {
        this.lastAssetValue = lastAssetValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_mgt.last_time
     *
     * @return the value of inventory_mgt.last_time
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_mgt.last_time
     *
     * @param lastTime the value for inventory_mgt.last_time
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_mgt.last_opr
     *
     * @return the value of inventory_mgt.last_opr
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public String getLastOpr() {
        return lastOpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_mgt.last_opr
     *
     * @param lastOpr the value for inventory_mgt.last_opr
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setLastOpr(String lastOpr) {
        this.lastOpr = lastOpr == null ? null : lastOpr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_mgt.job_flag
     *
     * @return the value of inventory_mgt.job_flag
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public Integer getJobFlag() {
        return jobFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_mgt.job_flag
     *
     * @param jobFlag the value for inventory_mgt.job_flag
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setJobFlag(Integer jobFlag) {
        this.jobFlag = jobFlag;
    }
}