package com.fhq.model;

import java.util.Date;

public class Login {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.id_key
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    private Integer idKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.role_id
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.account
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.password
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.last_time
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    private Date lastTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.jobflag
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    private Integer jobflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.id_key
     *
     * @return the value of login.id_key
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public Integer getIdKey() {
        return idKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.id_key
     *
     * @param idKey the value for login.id_key
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public void setIdKey(Integer idKey) {
        this.idKey = idKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.role_id
     *
     * @return the value of login.role_id
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.role_id
     *
     * @param roleId the value for login.role_id
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.account
     *
     * @return the value of login.account
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.account
     *
     * @param account the value for login.account
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.password
     *
     * @return the value of login.password
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.password
     *
     * @param password the value for login.password
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.last_time
     *
     * @return the value of login.last_time
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.last_time
     *
     * @param lastTime the value for login.last_time
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.jobflag
     *
     * @return the value of login.jobflag
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public Integer getJobflag() {
        return jobflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.jobflag
     *
     * @param jobflag the value for login.jobflag
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public void setJobflag(Integer jobflag) {
        this.jobflag = jobflag;
    }
}