package com.fhq.model;

import java.util.Date;

public class OprRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opr_record.id_key
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private Integer idKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opr_record.opr
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private String opr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opr_record.opr_ip
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private String oprIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opr_record.opr_time
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private Date oprTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opr_record.record_time
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private Date recordTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opr_record.job_flag
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private Integer jobFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opr_record.opr_content
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private String oprContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opr_record.id_key
     *
     * @return the value of opr_record.id_key
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public Integer getIdKey() {
        return idKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opr_record.id_key
     *
     * @param idKey the value for opr_record.id_key
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setIdKey(Integer idKey) {
        this.idKey = idKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opr_record.opr
     *
     * @return the value of opr_record.opr
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public String getOpr() {
        return opr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opr_record.opr
     *
     * @param opr the value for opr_record.opr
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setOpr(String opr) {
        this.opr = opr == null ? null : opr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opr_record.opr_ip
     *
     * @return the value of opr_record.opr_ip
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public String getOprIp() {
        return oprIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opr_record.opr_ip
     *
     * @param oprIp the value for opr_record.opr_ip
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setOprIp(String oprIp) {
        this.oprIp = oprIp == null ? null : oprIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opr_record.opr_time
     *
     * @return the value of opr_record.opr_time
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public Date getOprTime() {
        return oprTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opr_record.opr_time
     *
     * @param oprTime the value for opr_record.opr_time
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setOprTime(Date oprTime) {
        this.oprTime = oprTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opr_record.record_time
     *
     * @return the value of opr_record.record_time
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opr_record.record_time
     *
     * @param recordTime the value for opr_record.record_time
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opr_record.job_flag
     *
     * @return the value of opr_record.job_flag
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public Integer getJobFlag() {
        return jobFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opr_record.job_flag
     *
     * @param jobFlag the value for opr_record.job_flag
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setJobFlag(Integer jobFlag) {
        this.jobFlag = jobFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opr_record.opr_content
     *
     * @return the value of opr_record.opr_content
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public String getOprContent() {
        return oprContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opr_record.opr_content
     *
     * @param oprContent the value for opr_record.opr_content
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setOprContent(String oprContent) {
        this.oprContent = oprContent == null ? null : oprContent.trim();
    }
}