package com.fhq.model;

import java.util.Date;

public class RoleAuthMgt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_auth_mgt.id_key
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private Integer idKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_auth_mgt.role_id
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_auth_mgt.role
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_auth_mgt.auth_id
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private String auth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_auth_mgt.last_time
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private Date lastTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_auth_mgt.last_opr
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private String lastOpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_auth_mgt.job_flag
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    private Integer jobFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_auth_mgt.id_key
     *
     * @return the value of role_auth_mgt.id_key
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public Integer getIdKey() {
        return idKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_auth_mgt.id_key
     *
     * @param idKey the value for role_auth_mgt.id_key
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setIdKey(Integer idKey) {
        this.idKey = idKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_auth_mgt.role_id
     *
     * @return the value of role_auth_mgt.role_id
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_auth_mgt.role_id
     *
     * @param roleId the value for role_auth_mgt.role_id
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_auth_mgt.role
     *
     * @return the value of role_auth_mgt.role
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_auth_mgt.role
     *
     * @param role the value for role_auth_mgt.role
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_auth_mgt.auth_id
     *
     * @return the value of role_auth_mgt.auth_id
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public String getAuth() {
        return auth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_auth_mgt.auth_id
     *
     * @param auth the value for role_auth_mgt.auth_id
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setAuth(String auth) {
        this.auth = auth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_auth_mgt.last_time
     *
     * @return the value of role_auth_mgt.last_time
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_auth_mgt.last_time
     *
     * @param lastTime the value for role_auth_mgt.last_time
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_auth_mgt.last_opr
     *
     * @return the value of role_auth_mgt.last_opr
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public String getLastOpr() {
        return lastOpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_auth_mgt.last_opr
     *
     * @param lastOpr the value for role_auth_mgt.last_opr
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setLastOpr(String lastOpr) {
        this.lastOpr = lastOpr == null ? null : lastOpr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_auth_mgt.job_flag
     *
     * @return the value of role_auth_mgt.job_flag
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public Integer getJobFlag() {
        return jobFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_auth_mgt.job_flag
     *
     * @param jobFlag the value for role_auth_mgt.job_flag
     *
     * @mbg.generated Wed Jan 02 14:04:57 CST 2019
     */
    public void setJobFlag(Integer jobFlag) {
        this.jobFlag = jobFlag;
    }
}