package com.fhq.model;

import java.util.Date;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id_key
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    private Integer idKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.last_time
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    private Date lastTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.last_opr
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    private String lastOpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.job_flag
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    private Integer jobFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.account
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_nm
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    private String userNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gender
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.birth_date
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    private Date birthDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.mobile
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    private Integer mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.qq
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    private Integer qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.email
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id_key
     *
     * @return the value of user_info.id_key
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public Integer getIdKey() {
        return idKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id_key
     *
     * @param idKey the value for user_info.id_key
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public void setIdKey(Integer idKey) {
        this.idKey = idKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.last_time
     *
     * @return the value of user_info.last_time
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.last_time
     *
     * @param lastTime the value for user_info.last_time
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.last_opr
     *
     * @return the value of user_info.last_opr
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public String getLastOpr() {
        return lastOpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.last_opr
     *
     * @param lastOpr the value for user_info.last_opr
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public void setLastOpr(String lastOpr) {
        this.lastOpr = lastOpr == null ? null : lastOpr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.job_flag
     *
     * @return the value of user_info.job_flag
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public Integer getJobFlag() {
        return jobFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.job_flag
     *
     * @param jobFlag the value for user_info.job_flag
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public void setJobFlag(Integer jobFlag) {
        this.jobFlag = jobFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.account
     *
     * @return the value of user_info.account
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.account
     *
     * @param account the value for user_info.account
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_nm
     *
     * @return the value of user_info.user_nm
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public String getUserNm() {
        return userNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_nm
     *
     * @param userNm the value for user_info.user_nm
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public void setUserNm(String userNm) {
        this.userNm = userNm == null ? null : userNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gender
     *
     * @return the value of user_info.gender
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.gender
     *
     * @param gender the value for user_info.gender
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.birth_date
     *
     * @return the value of user_info.birth_date
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.birth_date
     *
     * @param birthDate the value for user_info.birth_date
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.mobile
     *
     * @return the value of user_info.mobile
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public Integer getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.mobile
     *
     * @param mobile the value for user_info.mobile
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public void setMobile(Integer mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.qq
     *
     * @return the value of user_info.qq
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public Integer getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.qq
     *
     * @param qq the value for user_info.qq
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public void setQq(Integer qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.email
     *
     * @return the value of user_info.email
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.email
     *
     * @param email the value for user_info.email
     *
     * @mbg.generated Thu Jan 24 10:39:41 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}